name: active_matrimonial_flutter_app
description: active_matrimonial_flutter_app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.9.5+19

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  one_context: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  expandable: ^5.0.1
  flutter_quill: ^7.2.4
  markdown: ^7.0.1
  shared_preferences: ^2.0.15
  flutter_facebook_auth: ^5.0.6
  twitter_login: ^4.2.3
  rename: ^2.0.1
  full_screen_image: any
  package_info_plus: ^4.0.0
  toast: ^0.3.0
  intl: ^0.18.0
  pinput: ^2.2.31
  email_validator: ^2.1.16
  google_fonts: ^4.0.4
  carousel_slider: ^4.1.1
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  http: ^0.13.5
  intl_phone_number_input: ^0.7.1
  image_picker: ^0.8.6
  multiselect: ^0.1.0
  webview_flutter: ^4.0.7
  firebase_auth: ^4.1.3
  google_sign_in: ^6.0.2
  firebase_core: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_swipable: ^1.2.1
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  flutter_summernote: ^1.0.0
  zoom_widget: ^2.0.0
  flutter_html: ^3.0.0-beta.1
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^16.1.0
  file_picker: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"


flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/icon/
    - assets/images/


